import { StyleSheet, Text, View } from 'react-native'
import React from 'react'

export default function Profile() {
  return (
    <View>
      <Text>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis facilis adipisci voluptas ipsam nulla praesentium quod temporibus dolor quam provident nostrum perspiciatis harum optio nihil atque odit, quaerat voluptates dolores quidem. Labore cupiditate totam magni, maiores, recusandae itaque ut impedit possimus ipsum libero neque assumenda odit enim voluptatum fuga earum accusantium blanditiis! Itaque quis porro et libero molestiae consequuntur saepe, eius enim explicabo blanditiis vero ducimus doloremque, facere dignissimos beatae, quasi debitis soluta molestias dolore sed. Itaque earum consectetur ipsam expedita, omnis porro iste nam perferendis impedit libero quidem nihil quae, vel maiores rerum, voluptate deserunt in est delectus ab. Aut, impedit ratione velit fugiat maiores repellendus, ea minus distinctio odit similique veniam laudantium molestias nisi in? Suscipit non aut beatae nulla obcaecati odio natus, eaque deleniti repudiandae quasi optio libero, est sit esse. Non sed pariatur molestiae perferendis officia minima, rerum cum sapiente molestias excepturi dolore quis odio eaque. Error similique sequi sapiente quo, dolore eos animi ex? Officiis excepturi eaque error aliquam rem molestiae maiores rerum sapiente nesciunt officia! Odit, amet est? Soluta distinctio reiciendis ipsam a dolor fuga perferendis? Vero repellat beatae, nihil eum quam molestiae reprehenderit porro. Maxime autem dolorem, voluptates, maiores repellat dolore tenetur ipsum veniam deserunt praesentium modi fugiat in fuga animi aperiam! Sint earum ratione, perferendis aperiam eveniet asperiores, numquam tempore a similique adipisci suscipit dolore magnam deserunt quasi fugit reprehenderit ea quos. Necessitatibus ea at natus provident placeat magnam maxime. Est assumenda nulla officiis sed incidunt. Quo incidunt doloribus asperiores non pariatur ipsa ducimus aspernatur aperiam voluptatibus magnam facilis corporis tempora nam at impedit laborum hic voluptate enim atque, velit odio perspiciatis ea. Necessitatibus quam dignissimos perferendis voluptas tenetur ipsa in? Cumque deleniti ducimus quia officiis optio dolor recusandae esse soluta. Quasi quidem autem cupiditate illo consequuntur nesciunt nam optio recusandae accusamus id quo error culpa ipsa sapiente quos aliquam explicabo eos, vel alias necessitatibus ut illum? Tenetur quisquam ipsam fuga nobis blanditiis aliquam nihil qui nisi pariatur est! Eaque provident quos eos. Explicabo corrupti non, repellendus asperiores quia ipsum temporibus expedita facere neque sed fuga recusandae voluptate aspernatur eligendi odio omnis placeat ratione voluptates eius. Quia quae dolorum voluptates enim. Quos pariatur quisquam ipsam accusantium modi earum porro qui quis vero itaque, optio tempora similique, aliquam dignissimos sint vel? Delectus quae quisquam optio doloremque! Sint, voluptatibus ex maiores, vitae pariatur est magni inventore incidunt, ipsam quas officia voluptates dolor omnis impedit.</Text>
    </View>
  )
}

const styles = StyleSheet.create({})